# Generated by Django 5.1.6 on 2025-03-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='プロフィール画像'),
        ),
    ]
