# Generated by Django 5.1.6 on 2025-03-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hardware_specs',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='ハードウェア環境'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_twitter',
            field=models.CharField(blank=True, max_length=100, verbose_name='X（旧Twitter）'),
        ),
    ]
