# Generated by Django 5.1.6 on 2025-03-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_hardware_specs_alter_profile_social_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_status',
            field=models.CharField(choices=[('available', '依頼受付中'), ('limited', '限定的に受付中'), ('unavailable', '依頼停止中')], default='unavailable', help_text='現在の仕事依頼の受付状況', max_length=20, verbose_name='仕事依頼ステータス'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_types',
            field=models.JSONField(blank=True, default=list, help_text='受付可能な仕事の種類（フロントエンド開発、バックエンド開発など）', verbose_name='受付可能な仕事タイプ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=dict, help_text='プログラミング言語、フレームワークなどの技術スキル', verbose_name='技術スキル'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specializations',
            field=models.JSONField(blank=True, default=list, help_text='開発の専門分野（Webアプリ、モバイルアプリなど）', verbose_name='専門分野'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_rate',
            field=models.CharField(blank=True, help_text='希望する報酬額や時給の目安', max_length=100, verbose_name='希望単価/時給'),
        ),
    ]
