# Generated by Django 5.1.6 on 2025-03-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_job_status_profile_job_types_profile_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='app_types_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発したアプリの種類と数', verbose_name='アプリ種類統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dev_status_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーのアプリの開発状況の統計', verbose_name='開発状況統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='genres_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発したアプリのジャンルと数', verbose_name='ジャンル統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='publish_status_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーのアプリの公開状態の統計', verbose_name='公開状態統計'),
        ),
    ]
