# Generated by Django 5.1.6 on 2025-03-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_app_types_stats_profile_dev_status_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpu_type_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発に使用しているCPUタイプの統計', verbose_name='CPU統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='device_type_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発に使用しているデバイス種類（Windows、Mac、Linuxなど）の統計', verbose_name='デバイス種類統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='internet_type_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発に使用しているインターネット接続タイプの統計', verbose_name='インターネット接続統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='memory_size_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発に使用しているメモリサイズの統計', verbose_name='メモリサイズ統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='monitor_count_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発に使用しているモニター数の統計', verbose_name='モニター数統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pc_type_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発に使用しているPCタイプ（デスクトップ・ノートなど）の統計', verbose_name='PCタイプ統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='storage_type_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発に使用しているストレージタイプの統計', verbose_name='ストレージタイプ統計'),
        ),
    ]
