# Generated by Django 5.1.6 on 2025-03-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_cpu_type_stats_profile_device_type_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_tools_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発で使用しているAPIツールの統計', verbose_name='APIツール統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ci_cd_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発で使用しているCI/CDツールの統計', verbose_name='CI/CDツール統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='communication_tools_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発で使用しているコミュニケーションツールの統計', verbose_name='コミュニケーションツール統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='editor_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発に使用しているエディタ/IDEの統計', verbose_name='エディタ統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='monitoring_tools_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発で使用しているモニタリングツールの統計', verbose_name='モニタリングツール統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_size_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発に参加しているチームのサイズ統計', verbose_name='チームサイズ統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='version_control_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発に使用しているバージョン管理システムの統計', verbose_name='バージョン管理統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='virtualization_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発に使用している仮想化ツールの統計', verbose_name='仮想化ツール統計'),
        ),
    ]
