# Generated by Django 5.1.6 on 2025-03-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_api_tools_stats_profile_ci_cd_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='architecture_pattern_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが採用しているアーキテクチャパターンの統計', verbose_name='アーキテクチャパターン統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='design_pattern_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが採用しているデザインパターンの統計', verbose_name='デザインパターン統計'),
        ),
    ]
