# Generated by Django 5.1.6 on 2025-03-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_architecture_pattern_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backend_framework_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが使用しているバックエンドフレームワークの統計', verbose_name='バックエンドフレームワーク統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='backend_language_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが使用しているバックエンド言語の統計', verbose_name='バックエンド言語統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='backend_package_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが使用しているバックエンドパッケージ/ライブラリの統計', verbose_name='バックエンドパッケージ統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='css_framework_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが使用しているCSSフレームワーク/スタイリングツールの統計', verbose_name='CSSフレームワーク統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='database_type_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが使用しているデータベース種類の統計', verbose_name='データベース種類統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='frontend_framework_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが使用しているフロントエンドフレームワークの統計', verbose_name='フロントエンドフレームワーク統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='frontend_language_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが使用しているフロントエンド言語の統計', verbose_name='フロントエンド言語統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='markup_language_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが使用しているマークアップ/スタイリング言語の統計', verbose_name='マークアップ言語統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='orm_tool_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが使用しているORMツールの統計', verbose_name='ORM統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ui_library_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが使用しているUIライブラリ/コンポーネントフレームワークの統計', verbose_name='UIライブラリ統計'),
        ),
    ]
