# Generated by Django 5.1.6 on 2025-03-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_auth_method_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg_development_days',
            field=models.FloatField(default=0.0, help_text='ユーザーのアプリ一つあたりの平均開発日数', verbose_name='平均開発日数'),
        ),
        migrations.AddField(
            model_name='profile',
            name='development_duration_distribution',
            field=models.JSONField(blank=True, default=dict, help_text='短期(30日以内)・中期(31-180日)・長期(181日以上)の開発プロジェクト分布', verbose_name='開発期間分布'),
        ),
        migrations.AddField(
            model_name='profile',
            name='development_duration_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーのアプリ開発期間の統計情報', verbose_name='開発期間統計'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_development_days',
            field=models.IntegerField(default=0, help_text='ユーザーの全アプリ開発の合計日数', verbose_name='合計開発日数'),
        ),
    ]
