# Generated by Django 5.1.6 on 2025-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_avg_development_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_months',
            field=models.JSONField(blank=True, default=list, help_text='ユーザーが活発に開発していた年月のリスト', verbose_name='活発な開発期間'),
        ),
        migrations.AddField(
            model_name='profile',
            name='app_development_periods',
            field=models.JSONField(blank=True, default=list, help_text='各アプリの開発期間情報のリスト', verbose_name='アプリ別開発期間'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_app_date',
            field=models.DateField(blank=True, help_text='ユーザーが開発した最初のアプリの開始日', null=True, verbose_name='最初のアプリ開発日'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_app_date',
            field=models.DateField(blank=True, help_text='ユーザーが開発した最新のアプリの終了日', null=True, verbose_name='最新のアプリ開発日'),
        ),
    ]
