# Generated by Django 5.1.6 on 2025-03-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_active_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dev_status_stats',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='publish_status_stats',
        ),
        migrations.AlterField(
            model_name='profile',
            name='api_tools_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発で使用しているAPIツール（Postman、Swagger、cURLなど）の統計', verbose_name='APIツール統計'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monitoring_tools_stats',
            field=models.JSONField(blank=True, default=dict, help_text='ユーザーが開発で使用しているモニタリングツール（Prometheus、Grafana、New Relicなど）の統計', verbose_name='モニタリングツール統計'),
        ),
    ]
