# Generated by Django 5.1.7 on 2025-03-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='伝えたいこと'),
        ),
    ]
