# Generated by Django 5.1.5 on 2025-02-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='アプリ名')),
                ('app_types', models.JSONField(default=list, help_text='選択可能な値: web_app, ios_app, android_app, windows_app, mac_app, linux_app, game, other', verbose_name='アプリの種類')),
                ('genres', models.JSONField(default=list, help_text='選択可能な値: sns, netshop, matching, learning_service, work, entertainment, daily_life, communication, healthcare, finance, news_media, food, travel, real_estate, education, recruitment, literature, art, music, pet, game, sports, academic, development_tool, api_service, cms, blog, portfolio, other', verbose_name='ジャンル')),
                ('other_genre', models.CharField(blank=True, max_length=50, verbose_name='その他のジャンル')),
                ('status', models.CharField(choices=[('completed', '完成'), ('in_development', '開発中'), ('draft', '非公開'), ('public', '公開')], default='draft', max_length=20, verbose_name='開発状況')),
                ('app_url', models.URLField(blank=True, verbose_name='アプリのURL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHubリポジトリURL')),
                ('overview', models.TextField(blank=True, verbose_name='アプリの概要')),
                ('motivation', models.TextField(blank=True, verbose_name='開発のきっかけ')),
                ('catchphrases', models.JSONField(default=list, verbose_name='キャッチコピー')),
                ('target_users', models.TextField(blank=True, verbose_name='ターゲットユーザー')),
                ('problems', models.TextField(blank=True, verbose_name='アプリの問題点')),
                ('final_appeal', models.TextField(blank=True, verbose_name='最後のアピール')),
                ('screenshots', models.JSONField(default=list, verbose_name='スクリーンショット')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'アプリギャラリー',
                'verbose_name_plural': 'アプリギャラリー',
            },
        ),
    ]
