# Generated by Django 5.1.6 on 2025-02-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_gallery', '0002_app_gallery_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgallery',
            name='thumbnail',
            field=models.JSONField(blank=True, help_text='アプリのサムネイル画像情報', null=True, verbose_name='サムネイル画像'),
        ),
        migrations.AlterField(
            model_name='appgallery',
            name='dev_status',
            field=models.CharField(choices=[('completed', '完成品'), ('in_development', '開発中')], default='in_development', max_length=20, verbose_name='開発状況'),
        ),
    ]
