# Generated by Django 5.1.6 on 2025-02-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_gallery', '0005_alter_appgallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgallery',
            name='hardware_specs',
            field=models.JSONField(blank=True, default=dict, help_text='開発時に使用したパソコンのスペック情報', verbose_name='開発環境のスペック'),
        ),
    ]
