# Generated by Django 5.1.6 on 2025-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_gallery', '0007_appgallery_development_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgallery',
            name='backend',
            field=models.JSONField(blank=True, default=dict, help_text='バックエンド関連の情報（メイン言語、フレームワーク、パッケージなど）', verbose_name='バックエンド情報'),
        ),
    ]
