# Generated by Django 5.1.6 on 2025-02-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_gallery', '0008_appgallery_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgallery',
            name='architecture',
            field=models.JSONField(blank=True, default=dict, help_text='アーキテクチャ関連の情報（アーキテクチャパターン、デザインパターン、説明など）', verbose_name='アーキテクチャ情報'),
        ),
    ]
