# Generated by Django 5.1.6 on 2025-02-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_gallery', '0009_appgallery_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgallery',
            name='database',
            field=models.JSONField(blank=True, default=dict, help_text='データベース関連の情報（種類、ホスティング、ORMなど）', verbose_name='データベース情報'),
        ),
        migrations.AddField(
            model_name='appgallery',
            name='frontend',
            field=models.JSONField(blank=True, default=dict, help_text='フロントエンド関連の情報（言語、フレームワーク、CSSフレームワークなど）', verbose_name='フロントエンド情報'),
        ),
        migrations.AddField(
            model_name='appgallery',
            name='security',
            field=models.JSONField(blank=True, default=dict, help_text='セキュリティ関連の情報（認証方式、セキュリティ対策など）', verbose_name='セキュリティ情報'),
        ),
    ]
