# Generated by Django 5.1.6 on 2025-03-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_gallery', '0010_appgallery_database_appgallery_frontend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgallery',
            name='development_story',
            field=models.JSONField(blank=True, default=dict, help_text='開発ストーリー関連の情報（開発期間、工夫したポイント、苦労した点など）', verbose_name='開発ストーリー情報'),
        ),
    ]
