# Generated by Django 5.1.6 on 2025-03-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_gallery', '0011_add_development_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0, verbose_name='閲覧数')),
                ('like_count', models.IntegerField(default=0, verbose_name='いいね数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='コメント数')),
                ('share_count', models.IntegerField(default=0, verbose_name='共有数')),
                ('daily_views', models.JSONField(default=dict, help_text='各日付の閲覧数を記録', verbose_name='日別閲覧数')),
                ('regional_views', models.JSONField(default=dict, help_text='各地域からの閲覧数を記録', verbose_name='地域別閲覧数')),
                ('referrers', models.JSONField(default=dict, help_text='アクセス元サイトと回数を記録', verbose_name='リファラー情報')),
                ('device_types', models.JSONField(default=dict, help_text='閲覧に使用されたデバイスタイプ（PC, モバイル, タブレット）', verbose_name='デバイスタイプ')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='apps_gallery.appgallery', verbose_name='アプリ')),
            ],
            options={
                'verbose_name': 'アプリアナリティクス',
                'verbose_name_plural': 'アプリアナリティクス',
            },
        ),
    ]
