# Generated by Django 5.1.6 on 2025-03-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_gallery', '0012_appanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgallery',
            name='hosting',
            field=models.JSONField(blank=True, default=dict, help_text='ホスティング関連の情報（Webアプリケーションホスティング、デプロイ方法など）', verbose_name='ホスティング情報'),
        ),
    ]
