# Generated by Django 5.1.6 on 2025-03-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_gallery', '0013_appgallery_hosting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appgallery',
            name='dev_status',
            field=models.CharField(choices=[('completed', '完成品'), ('in_development', '開発中'), ('beta', 'ベータ版')], default='in_development', max_length=20, verbose_name='開発状況'),
        ),
    ]
